### ISSUE TITLE
Add Rails 5 Example

### ISSUE THREAD

**Issue by athix** [Sorcery/sorcery-example-app#2]

**Comment by Ch4s3** [comment]
I haven't used rails 5 yet, so this might be interesting. Perhaps this should wait for `0.10`?

**Comment by athix** [comment]
As far as I can tell, 0.9.1 is actually broken in some regards for Rails 5, so definitely would wait until after 0.10.0 to get started on a Rails 5 example.

There's a lot of interesting changes in Rails 5, might be a fun project if you want to take it on @Ch4s3.

**Comment by Ch4s3** [comment]
I'll try to take a look this weekend, depending on how New Year's shakes out.

**Comment by mladenilic** [comment]
@athix with #5 merged, do you think we can close this one?

**Comment by athix** [comment]
@mladenilic I'm on the fence. It's still missing some Rails 5 stuff (e.g. models not inheriting from ApplicationModel) but it is technically using Rails 5. If we generated a fresh Rails 5 app and dragged the code on top of that, I would feel more comfortable saying that it's good to go.

**Comment by dankimio** [comment]
I think it's close enough to what we want. If we need to add something else that affects Sorcery in any way, we can add that in a separate PR. So I'm closing the issue for now.
